<a href="https://colab.research.google.com/github/OmPanchal/Learning-Tensorflow/blob/main/00_tensorflow_fundamentals.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

## **In this notebook we are going to cover the most fundamental concepts of tensors using tensorflow**

### **Contents**:
* Introduction to tensors 
* Get info from tensors
* Manipulating the tensors
* Tensors in NumPy
* Using at @tf.function (using GPUs with Tf)
* Excercises


## **Introduction to tensors**

### ⭐ Creating tensors with `tf.constant`

In [ ]:
import tensorflow as tf 
print(tf.__version__)

2.8.0


In [ ]:
# creating tensors with tf.constant()
scalar = tf.constant(7)
scalar
# shape = "()" since it is only a scalar

<tf.Tensor: shape=(), dtype=int32, numpy=7>

In [ ]:
# Check the number of dimensions of a tensor (ndim == number of dimensions)
scalar.ndim

0

In [ ]:
# Create a vector
vector = tf.constant([10, 10])
vector

<tf.Tensor: shape=(2,), dtype=int32, numpy=array([10, 10], dtype=int32)>

In [ ]:
# Check the dimensions of the vector
vector.ndim

1

In [ ]:
# Create a matrix (has more than 1 dimension)
matrix = tf.constant([[1, 1],
                      [2, 2]])

matrix

<tf.Tensor: shape=(2, 2), dtype=int32, numpy=
array([[1, 1],
       [2, 2]], dtype=int32)>

In [ ]:
# Check the number of dimensions of the matrix
matrix.ndim

2

In [ ]:
# Create another matrix and specify the data type with dtype
another_matrix = tf.constant([[1., 2., 3.],
                              [4., 5., 6.],
                              [7., 8., 9.]], dtype=tf.float16)
another_matrix # Changes the data type of the tensor 

<tf.Tensor: shape=(3, 3), dtype=float16, numpy=
array([[1., 2., 3.],
       [4., 5., 6.],
       [7., 8., 9.]], dtype=float16)>

In [ ]:
# Number of dimensions of another_matrix
another_matrix.ndim

# -- Total number of dimensions is equal to the number of elements in the shape of the tensor --

2

In [ ]:
# Increase the number of dimensions
larger_matrix = tf.constant([[ [1, 2] , [3, 4] ],
                             [ [5, 6] , [7, 8] ],
                             [ [9, 10] , [11, 12] ]])
larger_matrix

<tf.Tensor: shape=(3, 2, 2), dtype=int32, numpy=
array([[[ 1,  2],
        [ 3,  4]],

       [[ 5,  6],
        [ 7,  8]],

       [[ 9, 10],
        [11, 12]]], dtype=int32)>

In [ ]:
# Number of dimensions in larger_matrix
larger_matrix.ndim

### -- This "larger_matrix" can also be called a tensor
### -- But technically the same thing

3

### 📗 **What we have created so far**
* **Scalar** : a single number
* **Vector** : a number with a direction (e.g. wind speed and direction)
* **Matrix** : a 2 dimensional vector
* **Tensor** : an n-dimensional array of numbers, where n can be any number (e.g. 7 dimensions)

### ⭐ Creating tensors with `tf.Variable`

In [ ]:
# This is a changeable tensor
changeable_tensor = tf.Variable([1, 2, 3, 4])
unchangeable_tensor = tf.constant([1, 2 ,3, 4])
changeable_tensor, unchangeable_tensor

(<tf.Variable 'Variable:0' shape=(4,) dtype=int32, numpy=array([1, 2, 3, 4], dtype=int32)>,
 <tf.Tensor: shape=(4,), dtype=int32, numpy=array([1, 2, 3, 4], dtype=int32)>)

In [ ]:
# Try to change one of the elements in the changeable tensor
# changeable_tensor[0] = 10
# changeable_tensor
# -- ERROR --

### ⭐ Change the value of the elements in a tensor with `.assign`



In [ ]:
# Use .assign function
changeable_tensor[0].assign(10)
changeable_tensor 
# Works

<tf.Variable 'Variable:0' shape=(4,) dtype=int32, numpy=array([10,  2,  3,  4], dtype=int32)>

In [ ]:
# Try to change the value in the unchangable tensor
unchangeable_tensor[0].assign(2)
unchangeable_tensor
# Does not work as it is a constant tensor

AttributeError: ignored

##### 🔑 **NOTE:** You are rarely going to have the decide whether to use `tf.constant` or `tf.Variable`. Tensorflow will do this for you in the background

### ⭐ Creating random tensors with `tf.random`

In [ ]:
# Radom tensors are tensors of some arbitrary size containing random numbers
# -- Used to initialize weights in neural networks

# Function takes the shape of the tensor, the minumum value and the maximum value
random_arr = tf.random.uniform(shape=[2, 2]) # Uniform Distribution
random_arr2 = tf.random.normal(shape=[2, 2]) # Normal Distribution

random_arr, random_arr2

In [ ]:
# Creating Random Tensors with a seed

random_arr3 = tf.random.Generator.from_seed(123)
random_arr3 = random_arr3.normal(shape=[2, 2])

random_arr4 = tf.random.Generator.from_seed(123)
random_arr4 = random_arr4.normal(shape=[2, 2])

random_arr3, random_arr4, random_arr3 == random_arr4

### ⭐ Shuffle the order of the elements in a tensor with `tf.random.shuffle`

In [ ]:
# Shuffle the tensor (Good when you don't want the order of your data to affect the learning patterns)
not_shuffled = tf.constant([[1, 2],
                           [3, 4],
                           [5, 6]])

tf.random.set_seed(123)
not_shuffled = tf.random.shuffle(not_shuffled)

# -- Shuffled along the first element --
not_shuffled

##### 📚 **Exercise:** Look through the TensorFlow Documentation on [Random Seed Generation](https://www.tensorflow.org/api_docs/python/tf/random/set_seed). Write 5 radom tensors and shuffle them.

##### If we want our shuffled tensor to be in the same order, we need to set the global seed and the operation level seed.
##### **🧪 What I found out:** 

> **Rule 4**: "If both the global and the operation seed are set: Both seeds are used in conjunction to determine the random sequence".

```
tf.random.set_seed(1234) # set the global seed
tf.random.shuffle(tensor, seed=1234) # set the operation level seed
```

In [ ]:
# make 5 random arrays
arr1 = tf.random.uniform(shape=[1, 2])
arr2 = tf.random.uniform(shape=[2, 2, 3])
arr3 = tf.random.normal(shape=[1])
arr4 = tf.random.normal(shape=[1, 2, 2, 1])
arr5 = tf.random. uniform(shape=[3])

arr1, arr2, arr3, arr4, arr5

In [ ]:
# shuffle the tensors
arr1shuff = tf.random.shuffle(arr1)
arr2shuff = tf.random.shuffle(arr2)
arr3shuff = tf.random.shuffle(arr3)
arr4shuff = tf.random.shuffle(arr4)
arr5shuff = tf.random.shuffle(arr5)

# -- All shuffled along the first elements --
arr1shuff, arr2shuff, arr3shuff, arr4shuff, arr5shuff

### ⭐ Other ways to make a tensor

In [ ]:
# Creates a tensor of any given shape with all elements equal to one
tf.ones([3, 3]) 

In [ ]:
# Creates a tensor of all zeros
tf.zeros([3, 3])

##### 🔑 **Note:** The main difference between Numpy arrays and Tensorflow tensors is that, tensors can be run on a GPU which is much faster for numerical computation

### ⭐ Tensors from Numpy arrays

In [ ]:
import numpy as np 

# Create a numpy array
numpy_A = np.arange(1, 26, dtype=np.int32)
numpy_A

# Convert it to a tensor
"""
The shape of the tensor should multiply to equal to
 the number of elements in the tensor
""" 
tensor_A = tf.constant(numpy_A, shape=[5, 5]) # Tensor
tensor_B = tf.constant(numpy_A) # Vector

tensor_A, tensor_B

### ⭐ Getting more information from tensors
 🔑 Different attibutes of a tensor:
* Shape (number of elements in each dimension of a tensor) | `tensor.shape`
* Rank (number of dimensions in a tensor) | `tensor.ndim`
* Axis or Dimension (particular dimension of a tensor) | `tensor[0], tensor[:, 1]`
* Size (total number of items in the tensor) | `tf.size(tensor)`

In [ ]:
# 4 dimension tensor
rank_4_tensor = tf.zeros(shape=[1, 2, 3, 4])
rank_4_tensor

In [ ]:
rank_4_tensor[:, :, 0]

In [ ]:
rank_4_tensor.shape, rank_4_tensor.ndim, rank_4_tensor[:, 1], tf.size(rank_4_tensor)

In [ ]:
# Get different atributes of our tensors
print("Datatype of every elements:", rank_4_tensor.dtype)
print("Shape of the tensor:", rank_4_tensor.shape)
print("Number of dimensions of the tensor:", rank_4_tensor.ndim)
print("Number of elements along 0 axis:", rank_4_tensor.shape[0])
print("Number of elements along last axis:", rank_4_tensor.shape[-1])
print("Total number of elements:", tf.size(rank_4_tensor).numpy())
# .numpy() turns it into an integer


### 📗 Why is this used?
This is used as not all tensors that you come across can be visualized easily. Due to this we use different attributes of the tensor to access different information about them.

### ⭐Indexing Tensors

Tensors can be indexed just like normal python lists

In [ ]:
# Get the first 2 elements of each dimension 
rank_4_tensor[:2, :2, :2, :2]

In [ ]:
# Get first element from each dimansion from each index except for the final one 
rank_4_tensor[:1, :, :1, :1]

In [ ]:
# Changing the shape od a tensor

# Create a rank 2 tensor (2 dimensions)
rank_2_tensor = tf.constant([[1, 2], 
                             [3, 4]])

rank_2_tensor.shape, rank_2_tensor.ndim

In [ ]:
# Get last item of each row of the rank 2 tensor
rank_2_tensor[:, -1]

### ⭐ Add new dimension to an existing tensor with `tf.newaxis`

In [ ]:
# Add in an extra dimension to out rank 2 tensor
# Change the rank 2 tensor to a rank 3 tensor, but keep the same values

rank_3_tensor = rank_2_tensor[..., tf.newaxis]
rank_3_tensor


### ⭐ Add new dimension to an existing tensor with `tf.expand_dims`

In [ ]:
# Alternative to tf.newaxis
tf.expand_dims(rank_2_tensor, axis=-1) # -1 means expand at the final axis

In [ ]:
tf.expand_dims(rank_2_tensor, axis=0) # Adds new dimension to first axis

In [ ]:
# only adds different axis to the tensor, does not change any of the values within the tensor
rank_2_tensor 

### ⭐ Manipulating Tensors (Tensor operations)
**Basic Math Operations :** 
`+`, `-`, `*`, `/`

In [ ]:
# You can add values to a tensor using the addition operator
tensor = tf.constant([[1, 2],
                      [3, 4]])

tensor + 10 # Adds 10 to all elements to a tensor
# ^ This works for all operations

##### 🔑 **NOTE :** When manipultaing tensors, the origional tensor stays the same, to overwrite the value of the origional tensor, you have the reassign the variable with the changed tensor

In [ ]:
#  Origional tensor does not change 
tensor

In [ ]:
# Multiplication
tensor * 10

In [ ]:
# Subtraction
tensor - 10

In [ ]:
# Tensorflow built-in functions can also be used
tf.multiply(tensor, 10) # < Gives the same result

In [ ]:
mat1 = tf.constant([[1, 2, 3],
                    [4, 5, 6]])
mat2 = tf.linalg.matrix_transpose(mat1)

tf.linalg.matmul(mat1, mat1, transpose_b=True )

In [ ]:
x = tf.constant([2., 0., 0., 0.])
y = tf.constant([-2., 0., 2., 5])

tf.math.add_n([x, x, x]) # Adds an "n" amount of tensors together


In [ ]:
tf.math.reciprocal(x) # Calculates the reciprocal
tf.math.reciprocal_no_nan(x) # Safe reciprocal calculation (accocunts for zeros)

In [ ]:
std1 = tf.constant([1, 1, 5, 10, 13, 20], dtype=tf.float16)  
std2 = tf.constant([28, 29, 30, 31, 32], dtype=tf.float16)
# -- Has to be float --

tf.math.reduce_std(std1), tf.math.reduce_std(std2)

In [ ]:

tf.linalg.normalize(tf.constant([1, 2, 3, 4], dtype=tf.float32))

### ⭐ Matrix Multiplication 1
##### 📗 **Matrix Multiplication is one of the most common operations in deep learning**
##### There are two rules for out tensors you need to multiply them
1. The inner dimensions **must match**
2. The resulting matrix has the shaope of the **outer** dimensions

In [ ]:
# Matrix multiplication in tensorflow

A = tf.constant([[1, 2, 3], 
                 [4, 5, 6]])
B = tf.constant([[6, 5], 
                 [4, 3],
                 [2, 1]])

tf.linalg.matmul(A, B)

In [ ]:
# Just multiplying will not work
A * tf.transpose(B) # Done element-wise

In [ ]:
# Done in python with @ operator
A @ B # Gives the same output 

##### 📚 **Exercise :** Recreate the matrix mjultiplication on the video and recreate it on tensorflow

In [ ]:
# Exercise
MatA = tf.constant([[1, 2, 5],
                    [7, 2, 1],
                    [3, 3, 3]])

MatB = tf.constant([[3, 5],
                    [6, 7],
                    [1, 8]])

# Using tensorflow and normal python operator
tf.matmul(MatA, MatB), MatA @ MatB

##### 📖 **Resource**: Information on [Matrix Multiplication](https://www.mathsisfun.com/algebra/matrix-multiplying.html)


In [ ]:
B.shape, A.shape, (A @ B).shape

In [ ]:
# Recreatioin of the example from matrix multiplication source

C = tf.constant([[13, 9, 7, 15],
                 [8, 7, 4, 6 ],
                 [6, 4, 0, 3]])

D = tf.constant([3, 4, 2])
C = tf.transpose(C)

C.shape, D.shape, tf.linalg.matvec(C, D)


In [ ]:
X = tf.constant([[1, 2, 3],
                 [4, 5, 6],
                 [7, 8, 9]])

Y = tf.constant([[1, 2, 3],
                 [4, 5, 6]])

X @ Y # Gives invalid matrix error

In [ ]:
X.shape, Y.shape
# Get the shapes of the matricies
# ^ Inner numbers do not match

# Reshape Y
Ynew = tf.reshape(Y, shape=(3, 2))

tf.matmul(X, Ynew)

In [ ]:
MatrixA = tf.constant([[1, 2],
                       [1, 2],
                       [1, 2]])

MatrixB = tf.constant([[1, 2],
                       [1, 2],
                       [1, 2]])


In [ ]:
# This is MatA * MatB
MatrixA.shape, MatrixB.shape, MatrixA @ tf.reshape(MatrixB, shape=(2, 3))

In [ ]:
# This is MatB * MatA
MatrixA.shape, MatrixB.shape, tf.reshape(MatrixA, shape=(2, 3)) @ MatrixB

# Both MatA * MatB and MatB * MatA give two different values
# therefore AB != BAf

In [ ]:
# Try matrix multiplication with transpose instead of reshape
MatrixA.shape, MatrixB.shape, tf.transpose(MatrixA) @ MatrixB

In [ ]:
MatrixA.shape, MatrixB.shape, MatrixA @ tf.transpose(MatrixB)

### ⭐ The dot product

Matrix Multiplication is also referred to as the dot product.

You can perform matrix multiplication using:
* `tf.matmul` (matrix multiplication)
* `tf.tensordot` (tensor fot product)

In [ ]:
X = tf.constant([[1, 2],
                 [3, 4],
                 [5, 6]])
Y = tf.constant([[7, 8 ], 
                [9, 10],
                [11, 12]])

X, Y

(<tf.Tensor: shape=(3, 2), dtype=int32, numpy=
 array([[1, 2],
        [3, 4],
        [5, 6]], dtype=int32)>, <tf.Tensor: shape=(3, 2), dtype=int32, numpy=
 array([[ 7,  8],
        [ 9, 10],
        [11, 12]], dtype=int32)>)

In [ ]:
tf.tensordot(tf.transpose(X), Y, axes=1)

<tf.Tensor: shape=(2, 2), dtype=int32, numpy=
array([[ 89,  98],
       [116, 128]], dtype=int32)>

In [ ]:
# matrix multiplication with Y being transposed
tf.matmul(X, tf.transpose(Y))

<tf.Tensor: shape=(3, 3), dtype=int32, numpy=
array([[ 23,  29,  35],
       [ 53,  67,  81],
       [ 83, 105, 127]], dtype=int32)>

In [ ]:
# Matrix multiplication with Y being reshaped
tf.matmul(X, tf.reshape(Y, shape=(2, 3)))

<tf.Tensor: shape=(3, 3), dtype=int32, numpy=
array([[ 27,  30,  33],
       [ 61,  68,  75],
       [ 95, 106, 117]], dtype=int32)>

##### 🔑 **Note:** **Transpose** flips the tensor over an axis while **reshape** changes shuffles the values in the tensor

In [ ]:
# Check the values of Y, reshaped Y and transposed Y
print("----Normal Y----")
print(Y, "\n")

print("----Reshaped Y----")
print(tf.reshape(Y, shape=[2, 3]), "\n")

print("----Transposed Y----")
print(tf.transpose(Y), "\n")

----Normal Y----
tf.Tensor(
[[ 7  8]
 [ 9 10]
 [11 12]], shape=(3, 2), dtype=int32) 

----Reshaped Y----
tf.Tensor(
[[ 7  8  9]
 [10 11 12]], shape=(2, 3), dtype=int32) 

----Transposed Y----
tf.Tensor(
[[ 7  9 11]
 [ 8 10 12]], shape=(2, 3), dtype=int32) 



##### 🔑 **Note:** Usually when performing matrix multiplcation on two tensor and one of the axes does not like up, you will transpose instead of reshape to satisfy the matrix multiplication rules

### ⭐ Changing the datatype of a tensor

In [ ]:
# Create a new tensor with default datatype (float32)
B = tf.constant([2.2, 5.8])
B.dtype

tf.float32

In [ ]:
C = tf.constant([7, 10])
C.dtype

tf.int32

In [ ]:
# Change from float32 to float16 (reduced precision)
B = tf.cast(B, dtype=tf.float16)
B, B.dtype

(<tf.Tensor: shape=(2,), dtype=float16, numpy=array([2.2, 5.8], dtype=float16)>,
 tf.float16)

In [ ]:
# Change from int32 to float32
D = tf.cast(C, dtype=tf.float32)
D

<tf.Tensor: shape=(2,), dtype=float32, numpy=array([ 7., 10.], dtype=float32)>

In [ ]:
D_float16 = tf.cast(D, dtype=tf.float16)
D_float16

<tf.Tensor: shape=(2,), dtype=float16, numpy=array([ 7., 10.], dtype=float16)>

### ⭐ Aggregating tensors

In [ ]:
# Get the absolute values
D = tf.constant([-7, -10])
D

<tf.Tensor: shape=(2,), dtype=int32, numpy=array([ -7, -10], dtype=int32)>

In [ ]:
# Get the absolute value
tf.abs(D)

<tf.Tensor: shape=(2,), dtype=int32, numpy=array([ 7, 10], dtype=int32)>

📗 Forms of tensor aggregation:
* Get tensor min
* Get tensor max 
* Get tensor mean
* Get sum of tensor

In [ ]:
# Get mean
D = tf.constant([-4, -10])
tf.reduce_mean(D)

<tf.Tensor: shape=(), dtype=int32, numpy=-7>

In [ ]:
# Get max
tf.reduce_max(D)

<tf.Tensor: shape=(), dtype=int32, numpy=-4>

In [ ]:
# Get min
tf.reduce_min(D)

<tf.Tensor: shape=(), dtype=int32, numpy=-10>

In [ ]:
# Get sum
tf.reduce_sum(D)

<tf.Tensor: shape=(), dtype=int32, numpy=-14>

In [ ]:
# new tensor with random values
import numpy as np
# You could either cast the datatype of the tensor or generate a random array and convert it to a tensor

randarr = np.random.uniform(low=0.5, high=13.3, size=(50))

E = tf.constant(randarr)
E = tf.cast(E, dtype=tf.float32)

E.shape, tf.size(E), E.ndim

(TensorShape([50]), <tf.Tensor: shape=(), dtype=int32, numpy=50>, 1)

##### 📚 **Exercise:** Using what you have learnt, find the variance and standard deviation of the tensor `E` using the tensorflow methods

In [ ]:
tf.math.reduce_variance(E), tf.math.reduce_std(E)

(<tf.Tensor: shape=(), dtype=float32, numpy=13.285015>,
 <tf.Tensor: shape=(), dtype=float32, numpy=3.6448615>)

##### You can also use the tensorflow probability library

In [ ]:
import tensorflow_probability as tfp

tfp.stats.variance(E), tfp.stats.stddev(E)

(<tf.Tensor: shape=(), dtype=float32, numpy=13.285015>,
 <tf.Tensor: shape=(), dtype=float32, numpy=3.6448615>)

### ⭐ Find the positional, maximum, minimum

In [ ]:
tf.random.set_seed(42)
F = tf.random.uniform(shape=[50])
F

<tf.Tensor: shape=(50,), dtype=float32, numpy=
array([0.6645621 , 0.44100678, 0.3528825 , 0.46448255, 0.03366041,
       0.68467236, 0.74011743, 0.8724445 , 0.22632635, 0.22319686,
       0.3103881 , 0.7223358 , 0.13318717, 0.5480639 , 0.5746088 ,
       0.8996835 , 0.00946367, 0.5212307 , 0.6345445 , 0.1993283 ,
       0.72942245, 0.54583454, 0.10756552, 0.6767061 , 0.6602763 ,
       0.33695042, 0.60141766, 0.21062577, 0.8527372 , 0.44062173,
       0.9485276 , 0.23752594, 0.81179297, 0.5263394 , 0.494308  ,
       0.21612847, 0.8457197 , 0.8718841 , 0.3083862 , 0.6868038 ,
       0.23764038, 0.7817228 , 0.9671384 , 0.06870162, 0.79873943,
       0.66028714, 0.5871513 , 0.16461694, 0.7381023 , 0.32054043],
      dtype=float32)>

In [ ]:
# Finds the indixes of the maximum and minimum value in the tensor
tf.math.argmax(F), tf.math.argmin(F)

(<tf.Tensor: shape=(), dtype=int64, numpy=42>,
 <tf.Tensor: shape=(), dtype=int64, numpy=16>)

In [ ]:
F[tf.math.argmax(F)], tf.reduce_max(F),

(<tf.Tensor: shape=(), dtype=float32, numpy=0.9671384>,
 <tf.Tensor: shape=(), dtype=float32, numpy=0.9671384>)

In [ ]:
# Check for euqality
F[tf.math.argmax(F)] == tf.reduce_max(F)

<tf.Tensor: shape=(), dtype=bool, numpy=True>

### ⭐ Squeezing a tensor (removing all single dimensions)

In [ ]:
# Create a tensor to get started
tf.random.set_seed(24)
G = tf.constant(tf.random.uniform(shape=[50]), shape=[1, 1, 1, 1, 1, 1, 1, 50])
G, G.shape

(<tf.Tensor: shape=(1, 1, 1, 1, 1, 1, 1, 50), dtype=float32, numpy=
 array([[[[[[[[0.10927987, 0.26020873, 0.7633631 , 0.9664098 ,
               0.6704161 , 0.5704179 , 0.11284781, 0.3750646 ,
               0.65140796, 0.25983608, 0.5361136 , 0.03527319,
               0.08702004, 0.8614912 , 0.25407887, 0.92887473,
               0.6599686 , 0.14698923, 0.3613621 , 0.9529114 ,
               0.5932065 , 0.9703479 , 0.9276773 , 0.79924107,
               0.21676326, 0.05454433, 0.2114675 , 0.38505208,
               0.23774743, 0.13890004, 0.22140944, 0.6960819 ,
               0.92024565, 0.35530853, 0.30598998, 0.72012484,
               0.45592606, 0.48967016, 0.98957   , 0.92758965,
               0.1983006 , 0.4531387 , 0.01492548, 0.5888916 ,
               0.33539438, 0.39484882, 0.31613898, 0.91811156,
               0.6128372 , 0.6474602 ]]]]]]]], dtype=float32)>,
 TensorShape([1, 1, 1, 1, 1, 1, 1, 50]))

In [ ]:
G = tf.squeeze(G)
G, G.shape

(<tf.Tensor: shape=(50,), dtype=float32, numpy=
 array([0.10927987, 0.26020873, 0.7633631 , 0.9664098 , 0.6704161 ,
        0.5704179 , 0.11284781, 0.3750646 , 0.65140796, 0.25983608,
        0.5361136 , 0.03527319, 0.08702004, 0.8614912 , 0.25407887,
        0.92887473, 0.6599686 , 0.14698923, 0.3613621 , 0.9529114 ,
        0.5932065 , 0.9703479 , 0.9276773 , 0.79924107, 0.21676326,
        0.05454433, 0.2114675 , 0.38505208, 0.23774743, 0.13890004,
        0.22140944, 0.6960819 , 0.92024565, 0.35530853, 0.30598998,
        0.72012484, 0.45592606, 0.48967016, 0.98957   , 0.92758965,
        0.1983006 , 0.4531387 , 0.01492548, 0.5888916 , 0.33539438,
        0.39484882, 0.31613898, 0.91811156, 0.6128372 , 0.6474602 ],
       dtype=float32)>, TensorShape([50]))

In [ ]:
H = tf.random.uniform(shape=[2, 1, 1, 2])
H, H.shape

(<tf.Tensor: shape=(2, 1, 1, 2), dtype=float32, numpy=
 array([[[[0.8875979 , 0.0716151 ]]],
 
 
        [[[0.38931954, 0.52773523]]]], dtype=float32)>,
 TensorShape([2, 1, 1, 2]))

In [ ]:
H = tf.squeeze(H)
H, H.shape

(<tf.Tensor: shape=(2, 2), dtype=float32, numpy=
 array([[0.8875979 , 0.0716151 ],
        [0.38931954, 0.52773523]], dtype=float32)>, TensorShape([2, 2]))

### ⭐ One hot encoding

In [ ]:
# indicies
indicies = [0, 1, 2, 3]

# One hot encoding
one_hot = tf.one_hot(indicies, depth=4, dtype=tf.float16)
one_hot

<tf.Tensor: shape=(4, 4), dtype=float16, numpy=
array([[1., 0., 0., 0.],
       [0., 1., 0., 0.],
       [0., 0., 1., 0.],
       [0., 0., 0., 1.]], dtype=float16)>

In [ ]:
# Can change the on and off values of the one hot encoding
tf.one_hot(indicies, depth=4, on_value=0.5, off_value=-0.5)

<tf.Tensor: shape=(4, 4), dtype=float32, numpy=
array([[ 0.5, -0.5, -0.5, -0.5],
       [-0.5,  0.5, -0.5, -0.5],
       [-0.5, -0.5,  0.5, -0.5],
       [-0.5, -0.5, -0.5,  0.5]], dtype=float32)>

### ⭐ More tensorflow math operations

In [ ]:
H = tf.range(1, 10, dtype=tf.float32)
H

<tf.Tensor: shape=(9,), dtype=float32, numpy=array([1., 2., 3., 4., 5., 6., 7., 8., 9.], dtype=float32)>

In [ ]:
# Square the tensor
tf.math.square(H)

<tf.Tensor: shape=(9,), dtype=int32, numpy=array([ 1,  4,  9, 16, 25, 36, 49, 64, 81], dtype=int32)>

In [ ]:
# Square root (requires non int type)
tf.math.sqrt(H) 

<tf.Tensor: shape=(9,), dtype=float32, numpy=
array([0.99999994, 1.4142134 , 1.7320508 , 1.9999999 , 2.236068  ,
       2.4494896 , 2.6457512 , 2.8284268 , 3.        ], dtype=float32)>

In [ ]:
# Log
tf.math.log(H)

<tf.Tensor: shape=(9,), dtype=float32, numpy=
array([0.       , 0.6931472, 1.0986123, 1.3862944, 1.609438 , 1.7917595,
       1.9459102, 2.0794415, 2.1972246], dtype=float32)>

In [ ]:
# compare 2 tensors
I = tf.constant([[1, 2, 3], 
                 [4, 5, 6]])
J = tf.constant([[1, 2, 3],
                 [1, 2, 3]])

# Finds x < y element-wise
tf.math.less(J, I)

<tf.Tensor: shape=(2, 3), dtype=bool, numpy=
array([[False, False, False],
       [ True,  True,  True]])>

In [ ]:
I = tf.cast(I, dtype=tf.double)

# cos
tf.math.cos(I)

<tf.Tensor: shape=(2, 3), dtype=float64, numpy=
array([[ 0.54030231, -0.41614684, -0.9899925 ],
       [-0.65364362,  0.28366219,  0.96017029]])>

In [ ]:
J = tf.cast(J, dtype=tf.float16)

# reciprocal
tf.math.reciprocal(J)

<tf.Tensor: shape=(2, 3), dtype=float16, numpy=
array([[1.    , 0.5   , 0.3333],
       [1.    , 0.5   , 0.3333]], dtype=float16)>

In [ ]:
K = tf.constant([0, -100, 100], dtype=tf.float64)

# Sigmoid
tf.math.sigmoid(K)

<tf.Tensor: shape=(3,), dtype=float64, numpy=array([5.00000000e-01, 3.72007598e-44, 1.00000000e+00])>

### ⭐ Tensors and Numpy Arrays

In [ ]:
# Can convert np arrays into a tensor
K = tf.constant(np.array([1., 2., 3., 4.]))
K, type(K)

(<tf.Tensor: shape=(4,), dtype=float64, numpy=array([1., 2., 3., 4.])>,
 tensorflow.python.framework.ops.EagerTensor)

In [ ]:
# Can convert from tensor to numpy array as well
K.numpy(), type(K.numpy())

(array([1., 2., 3., 4.]), numpy.ndarray)

In [ ]:
# Default types of each are different
numpy_K =  tf.constant(np.array([1., 2., 3., 4.]))
tensor_K = tf.constant([1., 2., 3., 4.])

# Default of numpy = float64 while default of tensor = float32
numpy_K.dtype, tensor_K.dtype

(tf.float64, tf.float32)